version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
build_script:
- ps: ./build_appveyor.ps1
test: off
artifacts:
- path: artifacts/dotnet-curses*.nupkg
only_commits:
  files:
    - dotnet-curses.sln
    - dotnet-curses/
deploy:
- provider: NuGet
  api_key:
    secure: UDW8eHW8VDRzr9YolMr6Cs2h6BaieEJvQASj/2xU1x+hG0LLZ8I6d2k0pQRl3oVi
  skip_symbols: true
  on:
    branch: master
- provider: GitHub
  auth_token:
    secure: +EUQOpgfGayDA+QMrOqaI9wi2mUYdI3RrTU2hJNTMAIfBm/HAIQkCPxIGx+8nDeA
  artifact: artifacts/dotnet-curses*.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
